### ISSUE TITLE
ImportError: No module named axolotladdress

### ISSUE THREAD

**Issue by ghost** [jlguardi/yowsup#12]
Hi Guys,

Could you please give me some help?
I´ve installed this version of Yowsup but I´m getting errors when I try to run: yowsup-cli demos -y -c CONFIG-FILE

It´s giving me this error:

`root@gcp1:/opt/yowsup# yowsup-cli demos -y -c yowsup-config.txt 
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 726, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1484, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 227, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 249, in startCmdline
    from yowsup.demos import cli
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/demos/cli/stack.py", line 2, in <module>
    from .layer import YowsupCliLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/demos/cli/layer.py", line 2, in <module>
    from yowsup.layers.interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/interface/__init__.py", line 1, in <module>
    from .interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/interface/interface.py", line 7, in <module>
    from yowsup.layers.axolotl.layer import YowAxolotlLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 26, in <module>
    from axolotl.axolotladdress import AxolotlAddress
ImportError: No module named axolotladdress
`

I don´t know how to fix this.

**Comment by cfenollosa** [comment]
You need to update python-axolotl to the develop branch

I'm typing it from memory, please make sure commands are right

```
(optional) pip remove python-axolotl
git clone https://github.com/tgalal/python-axolotl.git
cd python-axolotl
git checkout develop
python setup.py install
```

**Comment by ghost** [comment]
And that my friend, made it to work!!!!!

Thank you so much!

**Comment by ghost** [comment]
Only one thing in that line is wrong, the first line is:
**pip uninstall python-axolotl**
