### ISSUE TITLE
no such prekey error

### ISSUE THREAD

**Issue by thundergreen** [jlguardi/yowsup#15]
Hi guys. first of all GREAT WORK! Thanks for that! I'm using newest jlguardi master branch and newest axolotl from developer branch but never get sent ackn. or messages. I can send messages to other contacts.

Don't wanna bother just help to get yowsup running up again. Tha't why i post this traceback. If you don't need it. Just let me know and I will close this issue right away. Don't want to bother.

2016-03-29 19:58:09,453 ERROR transwhat: Traceback (most recent call last):  
  File "/opt/transwhat/transwhat.py", line 94, in <module>  
    asyncore.loop(timeout=1.0, count=10, use_poll=True)  
  File "/usr/lib/python2.7/asyncore.py", line 220, in loop  
    poll_fun(timeout, map)  
  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2  
    readwrite(obj, flags)  
  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite  
    obj.handle_error()  
  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite  
    obj.handle_read_event()  
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event  
    self.handle_read()  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/network/layer.py", line 88, in handle_read  
    self.receive(data)  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/network/layer.py", line 96, in receive  
    self.toUpper(data)  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/**init**.py", line 75, in toUpper  
    self.**upper.receive(data)  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive  
    self.processReceived()  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived  
    self.toUpper(oneMessageData)  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init**.py", line 75, in toUpper  
    self.**upper.receive(data)  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive  
    self.toUpper(payload)  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init**.py", line 75, in toUpper  
    self.**upper.receive(data)  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive  
    self.toUpper(node)  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init**.py", line 75, in toUpper  
    self.__upper.receive(data)  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 130, in receive  
    self.onMessage(protocolTreeNode)  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 152, in onMessage  
    self.handleEncMessage(protocolTreeNode)  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 224, in handleEncMessage  
    self.handlePreKeyWhisperMessage(node)  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 266, in handlePreKeyWhisperMessage  
    plaintext = sessionCipher.decryptPkmsg(preKeyWhisperMessage)  
  File "build/bdist.linux-armv7l/egg/axolotl/sessioncipher.py", line 96, in decryptPkmsg  
    unsignedPreKeyId = self.sessionBuilder.process(sessionRecord, ciphertext)  
  File "build/bdist.linux-armv7l/egg/axolotl/sessionbuilder.py", line 50, in process  
    unsignedPreKeyId = self.processV3(sessionRecord, message)  
  File "build/bdist.linux-armv7l/egg/axolotl/sessionbuilder.py", line 121, in processV3  
    parameters.setOurOneTimePreKey(self.preKeyStore.loadPreKey(message.getPreKeyId()).getKeyPair())  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 34, in loadPreKey  
    return self.preKeyStore.loadPreKey(preKeyId)  
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/store/sqlite/liteprekeystore.py", line 20, in loadPreKey  
    raise Exception("No such prekeyRecord!")  
Exception: No such prekeyRecord!

**Comment by jlguardi** [comment]
Send a text message to recipient.

**Comment by jlguardi** [comment]
https://github.com/tgalal/yowsup/issues/1180
No effective solution found by now.

**Comment by pranalik** [comment]
I  am also getting same error "raise Exception("No such prekeyRecord!")"

Can anyone help to solve

**Comment by jegue** [comment]
yeap same erro here! on messaging group!
    return self.preKeyStore.loadPreKey(preKeyId)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/store/sqlite/liteprekeystore.py", line 21, in loadPreKey
    raise Exception("No such prekeyRecord!")
