### ISSUE TITLE
Error sending messages

### ISSUE THREAD

**Issue by bkenny** [jlguardi/yowsup#21]
Getting the following error when trying to send a message after registering and getting a password successfully on the cli

```
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 231, in process
    self.startSendClient()
  File "/usr/local/bin/yowsup-cli", line 271, in startSendClient
    from yowsup.demos import sendclient
  File "/usr/local/lib/python2.7/site-packages/yowsup/demos/sendclient/__init__.py", line 1, in <module>
    from .stack import YowsupSendStack
  File "/usr/local/lib/python2.7/site-packages/yowsup/demos/sendclient/stack.py", line 2, in <module>
    from .layer import SendLayer
  File "/usr/local/lib/python2.7/site-packages/yowsup/demos/sendclient/layer.py", line 1, in <module>
    from yowsup.layers.interface                           import YowInterfaceLayer, ProtocolEntityCallback
  File "/usr/local/lib/python2.7/site-packages/yowsup/layers/interface/__init__.py", line 1, in <module>
    from .interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/usr/local/lib/python2.7/site-packages/yowsup/layers/interface/interface.py", line 7, in <module>
    from yowsup.layers.axolotl.layer import YowAxolotlLayer
  File "/usr/local/lib/python2.7/site-packages/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/usr/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 27, in <module>
    from axolotl.axolotladdress import AxolotlAddress
ImportError: No module named axolotladdress
```

using the following command

```
yowsup-cli demos --login NUMBER:PASSWORD -s NUMBER "test"
```

**Comment by jlguardi** [comment]
Read closed issues.
