### ISSUE TITLE
No attribute 'getChild' when sending message 

### ISSUE THREAD

**Issue by rump1992** [jlguardi/yowsup#4]
Hello there,

got this error when sending a message:

Auth: Logged in!
[connected]:/message send ########### test
[connected]:Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 227, in process
    self.startCmdline()
  File "yowsup-cli", line 255, in startCmdline
    stack.start()
  File "C:\Users\Dennis Rump\yowsup\yowsup\demos\cli\stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "C:\Users\Dennis Rump\yowsup\yowsup\stacks\yowstack.py", line 187, in loop
    asyncore.loop(_args, *_kwargs)
  File "C:\Users\Dennis Rump\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "C:\Users\Dennis Rump\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 150, in poll
    read(obj)
  File "C:\Users\Dennis Rump\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Users\Dennis Rump\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Users\Dennis Rump\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\network\layer.py", line 86, in handle_read
    self.receive(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\network\layer.py", line 94, in receive
    self.toUpper(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers__init__.py", line 59, in toUpper
    self.**upper.receive(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\stanzaregulator\layer.py", line 28, in receive
    self.processReceived()
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\stanzaregulator\layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\auth\layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\axolotl\layer.py", line 116, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers__init**.py", line 136, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\axolotl\layer.py", line 176, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\axolotl\layer.py", line 349, in onGetKeysResult
    entity = ResultGetKeysIqProtocolEntity.fromProtocolTreeNode(resultNode)
  File "C:\Users\Dennis Rump\yowsup\yowsup\layers\axolotl\protocolentities\iq_keys_get_result.py", line 88, in fromProtocolTreeNode
    preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'

**Comment by jlguardi** [comment]
Skipped but not fixed error in develop branch.
