### ISSUE TITLE
7bit ASCII encoding error

### ISSUE THREAD

**Issue by thundergreen** [jlguardi/yowsup#53]
2016-04-08 10:37:56,776 ERROR transwhat: Traceback (most recent call last):
  File "/opt/transwhat/transwhat.py", line 66, in handleTransportData
    plugin.handleDataRead(data)
  File "/opt/transwhat/Spectrum2/backend.py", line 414, in handleDataRead
    self.handleConvMessagePayload(wrapper.payload)
  File "/opt/transwhat/Spectrum2/backend.py", line 268, in handleConvMessagePayload
    self.handleMessageSendRequest(payload.userName, payload.buddyName, payload.message, payload.xhtml, payload.id)
  File "/opt/transwhat/whatsappbackend.py", line 66, in handleMessageSendRequest
    self.sessions[user].sendMessageToWA(buddy, message, ID, xhtml)
  File "/opt/transwhat/session.py", line 578, in sendMessageToWA
    waId = self.sendTextMessage(sender + '@s.whatsapp.net', message)
  File "/opt/transwhat/yowsupwrapper.py", line 168, in sendTextMessage
    self.sendEntity(messageEntity)
  File "/opt/transwhat/yowsupwrapper.py", line 567, in sendEntity
    entity = entity
  File "build/bdist.linux-armv7l/egg/yowsup/stacks/yowstack.py", line 176, in broadcastEvent
    if not self.**stackInstances[-1].onEvent(yowLayerEvent):
  File "/opt/transwhat/yowsupwrapper.py", line 600, in onEvent
    self.toLower(layerEvent.getArg('entity'))
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init**.py", line 79, in toLower
    self.**lower.send(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init**.py", line 192, in send
    s.send(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/**init**.py", line 130, in send
    send(entity)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/**init**.py", line 134, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "build/bdist.linux-armv7l/egg/yowsup/layers/**init**.py", line 79, in toLower
    self.__lower.send(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer.py", line 122, in send
    self.handlePlaintextNode(node)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer.py", line 190, in handlePlaintextNode
    messageData = self.serializeToProtobuf(node) if v2 else node.getChild("body").getData()
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer.py", line 502, in serializeToProtobuf
    return self.serializeTextToProtobuf(node)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer.py", line 510, in serializeTextToProtobuf
    m.conversation = node.getChild("body").getData()
  File "/usr/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 471, in field_setter
    self._fields[field] = type_checker.CheckValue(new_value)
  File "/usr/lib/python2.7/dist-packages/google/protobuf/internal/type_checkers.py", line 166, in CheckValue
    (proposed_value))
ValueError: 'Coucou.... U will visit us tonight? \xe2\x9c\x8c\xf0\x9f\x91\x8c\xf0\x9f\x91\x8a\xf0\x9f\x91\x8d' has type bytes, but isn't in 7-bit ASCII encoding. Non-ASCII strings must be converted to unicode objects before being added.

What does this mean?

**Comment by jlguardi** [comment]
@thundergreen Do not post trasnwhat issues. If you detect an issue with transwhat, reproduce with 

```
yowsup-cli demos -y -d -c configfile
```

and post log
