### ISSUE TITLE
Installation error due to missing symbol_database

### ISSUE THREAD

**Issue by necvga** [jlguardi/yowsup#57]
I will try message today found have follow problem:
Traceback (most recent call last):
  File "yowsup-cli", line 324, in <module>
    if not parser.process():
  File "yowsup-cli", line 228, in process
    self.startCmdline()
  File "yowsup-cli", line 250, in startCmdline
    from yowsup.demos import cli
  File "/run/shm/yowsup-master/yowsup/demos/cli/**init**.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/run/shm/yowsup-master/yowsup/demos/cli/stack.py", line 2, in <module>
    from .layer import YowsupCliLayer
  File "/run/shm/yowsup-master/yowsup/demos/cli/layer.py", line 2, in <module>
    from yowsup.layers.interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/run/shm/yowsup-master/yowsup/layers/interface/**init**.py", line 1, in <module>
    from .interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/run/shm/yowsup-master/yowsup/layers/interface/interface.py", line 7, in <module>
    from yowsup.layers.axolotl.layer import YowAxolotlLayer
  File "/run/shm/yowsup-master/yowsup/layers/axolotl/**init**.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/run/shm/yowsup-master/yowsup/layers/axolotl/layer.py", line 8, in <module>
    from yowsup.layers.axolotl.store.sqlite.liteaxolotlstore import LiteAxolotlStore
  File "/run/shm/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 2, in <module>
    from .liteidentitykeystore import LiteIdentityKeyStore
  File "/run/shm/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 4, in <module>
    from axolotl.util.keyhelper import KeyHelper
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/axolotl/util/keyhelper.py", line 10, in <module>
    from ..identitykeypair import IdentityKeyPair
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/axolotl/identitykeypair.py", line 3, in <module>
    from .state.storageprotos import IdentityKeyPairStructure
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/axolotl/state/storageprotos.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database

**Comment by jlguardi** [comment]
Remove google.protobuf 2 and install google.protobuf 3.

```
sudo apt-get remove python-protobuf‎
sudo python setup.py install
```

**Comment by necvga** [comment]
I was try 
sudo apt-get remove python-protobuf‎
sudo python setup.py install
after then , have follow error message
"
Traceback (most recent call last):
  File "yowsup-cli", line 324, in <module>
    if not parser.process():
  File "yowsup-cli", line 232, in process
    self.startSendClient()
  File "yowsup-cli", line 272, in startSendClient
    from yowsup.demos import sendclient
  File "/run/shm/yowsup-master/yowsup/demos/sendclient/**init**.py", line 1, in <module>
    from .stack import YowsupSendStack
  File "/run/shm/yowsup-master/yowsup/demos/sendclient/stack.py", line 2, in <module>
    from .layer import SendLayer
  File "/run/shm/yowsup-master/yowsup/demos/sendclient/layer.py", line 1, in <module>
    from yowsup.layers.interface                           import YowInterfaceLayer, ProtocolEntityCallback
  File "/run/shm/yowsup-master/yowsup/layers/interface/**init**.py", line 1, in <module>
    from .interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/run/shm/yowsup-master/yowsup/layers/interface/interface.py", line 7, in <module>
    from yowsup.layers.axolotl.layer import YowAxolotlLayer
  File "/run/shm/yowsup-master/yowsup/layers/axolotl/**init**.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/run/shm/yowsup-master/yowsup/layers/axolotl/layer.py", line 8, in <module>
    from yowsup.layers.axolotl.store.sqlite.liteaxolotlstore import LiteAxolotlStore
  File "/run/shm/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 2, in <module>
    from .liteidentitykeystore import LiteIdentityKeyStore
  File "/run/shm/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 4, in <module>
    from axolotl.util.keyhelper import KeyHelper
  File "build/bdist.linux-x86_64/egg/axolotl/util/keyhelper.py", line 10, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/identitykeypair.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/state/storageprotos.py", line 9, in <module>
ImportError: cannot import name symbol_database
"

**Comment by necvga** [comment]
I try reinstall python-axolotl
and remove ~/.yowsup/*
use python yowsup-cli demos -c config.file -y  , online .
the problem fix.
Thx

**Comment by egorovalexey27** [comment]
sudo apt-get remove python-protobuf‎
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python-protobuf‎

**Comment by egorovalexey27** [comment]
It helped that's http://stackoverflow.com/questions/26053982/error-setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-wit
And reinstall python-axolotl and protobuf
