### ISSUE TITLE
UnicodeDecodeError: 'ascii' ...

### ISSUE THREAD

**Issue by rigid** [jlguardi/yowsup#65]
I see those when unicode and str/bytes get mix in one format string:

```
2016-04-10 14:52:01,462 ERROR transwhat: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/transWhat/transwhat.py", line 100, in <module>
    asyncore.loop(timeout=1.0, count=10, use_poll = True)
  File "/usr/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 136, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 158, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 232, in handleEncMessage
    self.handleWhisperMessage(node)
File "/usr/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 316, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "/usr/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 365, in parseAndHandleMessageProto
    self.handleImageMessage(node, m.image_message)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 408, in handleImageMessage
    self.toUpper(messageNode)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 188, in receive
    s.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 124, in receive
    recv(node)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/protocol_media/layer.py", line 44, in recvMessageStanza
    self.toUpper(entity)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/interface/interface.py", line 78, in receive
    self.entity_callbacks[entityType](entity)
  File "/usr/lib/python2.7/site-packages/transWhat/yowsupwrapper.py", line 846, in onMessageReceived
    self.logger.debug("Received Message: %s" % entity)
  File "/usr/lib/python2.7/site-packages/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_image.py", line 40, in __str__
    out  = super(ImageDownloadableMediaMessageProtocolEntity, self).__str__()
  File "/usr/lib/python2.7/site-packages/yowsup/layers/protocol_media/protocolentities/message_media_downloadable.py", line 41, in __str__
    out += "File Hash: %s\n" % self.fileHash
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 11: ordinal not in range(128)
```

Instead of encoding the unicode string to ascii (and thus ignoring/replacing unconvertable characters), I'd propose a fix that makes all string literals unicode() by default in python2 and converting unicode to bytearray() where necessary:

```
diff --git a/yowsup/layers/network/layer.py b/yowsup/layers/network/layer.py
index 44b7f8e..6d257f2 100644
--- a/yowsup/layers/network/layer.py
+++ b/yowsup/layers/network/layer.py
@@ -1,3 +1,6 @@
+# use unicode encoding for all literals by default (for python2.x)
+from __future__ import unicode_literals
+
 from yowsup.layers import YowLayer, YowLayerEvent, EventCallback
 from yowsup.common.http.httpproxy import HttpProxy
 from yowsup.layers.network.layer_interface import YowNetworkLayerInterface
@@ -103,7 +106,7 @@ class YowNetworkLayer(YowLayer, asyncore.dispatcher_with_send):

     def send(self, data):
         if self.connected:
-            self.out_buffer = self.out_buffer + data
+            self.out_buffer = self.out_buffer + bytearray(data)
             self.initiate_send()

     def receive(self, data):
```

Would that be a practicable pull request? If yes, I would prepare one. Is there already a policy for string encoding in yowsup?

**Comment by freelo** [comment]
Hi, I don't see the relation between that `fileHash` issue and general yowsup string handling. I don't know how strings are handled within the protocol etc., but you should use unicode, so that there is no chance of misinterpreted encoding.

However, towards your reported issue:
Since the base64 encode was removed from that line some commits ago, I'd propose `self.fileHash.encode('hex')`.

**Comment by rigid** [comment]
True, there is no direct relation since i didn't realize that fileHash is of type str() and contains unprintable characters. .encode('hex') should fix it.
