### ISSUE TITLE
Error in receiveclient / echoclient

### ISSUE THREAD

**Issue by jcmeier** [jlguardi/yowsup#67]
Hi there,

I am playing around a bit with the example code from the demos folder. I copied the echoclient and modified it a bit to store the messages which it receives. When I am sending a messages with yowsup I get the following exception in the echoclient: 

Traceback (most recent call last):
  File "messagereceiver.py", line 11, in <module>
    stack.start()
  File "/home/jan/yowsup-playground/lib/receiveclient/stack.py", line 23, in start
    self.stack.loop()
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 195, in loop
  File "/usr/lib64/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib64/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib64/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 102, in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 110, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 75, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 75, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 75, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 33, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/decoder.py", line 16, in getProtocolTreeNode
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/decoder.py", line 252, in nextTreeInternal
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/decoder.py", line 276, in readList
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/decoder.py", line 268, in nextTreeInternal
TypeError: an integer is required

Any ideas what could be wrong?

Kind regards
Jan

**Comment by jlguardi** [comment]
Related with #17

**Comment by jcmeier** [comment]
Thanks for having an eye on the issue. If I can provide any help resolving this issue please contact me.

Kind regards
Jan

**Comment by chriso0710** [comment]
@jcmeier Did you find a solution? I am facing the same problem, see #22

**Comment by jcmeier** [comment]
@chriso0710  So far not. It is strange that if you run the command line client from demos this error does not happen. With the demos client you can send and receive without any problems. I do not know what is different there.

**Comment by jlguardi** [comment]
@jcmeier So the issue should be in your code!
Please check again and report.

**Comment by jcmeier** [comment]
Hi @jlguardi ,

I did some debugging on this issue.

The problem lies in yowsup/layers/coder/decoder.py line 269.

There is the following code:

`if nodeData:`
`nodeData = "".join(map(chr, nodeData))`

Which transforms an array of integers to chars and concanates them to a string.

In my case (sometimes, not every time), the "nodeData" is a string containing: 

"Replaced by new connection"

I do not know why this happens,

**Comment by jlguardi** [comment]
It means that you started other instance of yowsup or started official client with the same credentials.
The problem is that previous versions didn't produce this exception. I'll check now I know how to reproduce.

**Comment by jcmeier** [comment]
Ah great okay.

I handled this exception and test a bit and sending and receiving works fine. Maybe something is wrong with running the sender and receiver simultaneously but I am not really sure how I should implement it. Maybe that the messagereceiver is always connected is not a good idea.
