### ISSUE TITLE
<xml-not-well-formed> after handleVCardUpdatedRequest(user=xxxxxxx@domain.tld, nickname=ThUnD3r|Gr33n)

### ISSUE THREAD

**Issue by thundergreen** [jlguardi/yowsup#68]
```
2016-04-12 23:54:00,096 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,109 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,121 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,134 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,146 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,157 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,163 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,169 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,175 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,180 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,186 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,193 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,207 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,211 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,217 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,224 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,230 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,236 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,243 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,251 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,258 DEBUG WhatsAppBackend: handleStatusChangeRequest(user=thorsten@emevth.no-ip.biz, status=0, statusMessage=I'm available.)
2016-04-12 23:54:00,309 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:00,400 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:00,467 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:00,554 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:00,627 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:00,698 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:00,764 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:00,842 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:00,932 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:01,026 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:01,101 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:01,179 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:01,252 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:01,317 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:01,385 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:01,449 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:01,508 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:01,565 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:01,623 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:01,681 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:01,743 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:01,802 DEBUG WhatsAppBackend: handleVCardUpdatedRequest(user=thorsten@emevth.no-ip.biz, nickname=ThUnD3r|Gr33n)
2016-04-12 23:54:03,776 DEBUG WhatsAppBackend: handleVCardRequest(user=thorsten@emevth.no-ip.biz, buddy=thorsten, ID=82)
2016-04-12 23:54:03,777 DEBUG BuddyList: Requesting profile picture of 33781852856
2016-04-12 23:54:03,781 DEBUG BuddyList: Sending VCard (82) with image id <deferred.Deferred object at 0x758a3190>: <deferred.Deferred object at 0x758a3110>
2016-04-12 23:54:04,545 ERROR transwhat: Traceback (most recent call last):
  File "/opt/transwhat/transwhat.py", line 104, in <module>
    asyncore.loop(timeout=1.0, count=10, use_poll = True)
  File "/usr/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-armv7l/egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "build/bdist.linux-armv7l/egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer.py", line 145, in receive
    self.toUpper(protocolTreeNode)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 188, in receive
    s.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 124, in receive
    recv(node)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/auth/layer_authentication.py", line 92, in handleStreamError
    raise AuthError("Unhandled stream:error node:\n%s" % node)
AuthError: Unhandled stream:error node:
<stream:error>
<xml-not-well-formed>
</xml-not-well-formed>
</stream:error>
```

**Comment by jlguardi** [comment]
Upload logs from yowsup-cli.
