### ISSUE TITLE
'ascii' codec can't decode byte 0xf0

### ISSUE THREAD

**Issue by ghost** [jlguardi/yowsup#73]
```
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 324, in <module>

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 228, in process

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 256, in startCmdline

  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/stack.py", line 27, in start
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 187, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 102, in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 110, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 136, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 160, in onMessage
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 188, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 124, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/interface/interface.py", line 78, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/layer.py", line 529, in onMessage
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 0: ordinal not in range(128)
```

**Comment by dsiwer** [comment]
try encoding to 'utf-8'

**Comment by ghost** [comment]
It doesn't work

**Comment by jlguardi** [comment]
@montemarcaldera Please, update your code and check the installation/running conditions. I guess that you are using an old version of my code.

If error occurs again, please check again the installation and then post debug logs of cli, post how to reproduce this issue and I'll check again.
