### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by ganesansays** [jlguardi/yowsup#78]
Auth: Logged in!
[connected]:WARNING:axolotl.sessionbuilder:We've already setup a session for this V3 message, letting bundled message fall through...
ERROR:yowsup.layers.axolotl.layer:Received message with old counter: 3, 2
WARNING:yowsup.layers.axolotl.layer:Going to send the delivery receipt myself !
WARNING:axolotl.sessionbuilder:We've already setup a session for this V3 message, letting bundled message fall through...
[XXXXXXXXXXXX@s.whatsapp.net(09-04-2016 06:42)]:[YYYYYYYYYYYYYYYYYYYYY] [Media Type:image, Size:51493, URL:https://mmi720.whatsapp.net/d/oDRLA-3s3FEVseBS9dWvx1cIpHA/AhgbU7svOajHBYL1-ati4PkwiggCWu1pEeTSpl9Ro5HX.enc, FILE:/tmp/1D9F2095342FBE06D5080B8736CCD2.jpeg]
Message 1D9F2095342FBE06D5080B8736CCD2: Sent delivered receipt and Read
[connected]:
WARNING:yowsup.layers.axolotl.layer:No such prekeyRecord!
WARNING:yowsup.layers.axolotl.layer:No such prekeyRecord!
Traceback (most recent call last):
  File "./yowsup-cli", line 324, in <module>
    if not parser.process():
  File "./yowsup-cli", line 228, in process
    self.startCmdline()
  File "./yowsup-cli", line 256, in startCmdline
    stack.start()
  File "/home/ubuntu/yowsup/yowsup/demos/cli/stack.py", line 27, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/home/ubuntu/yowsup/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/ubuntu/yowsup/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/ubuntu/yowsup/yowsup/layers/**init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/ubuntu/yowsup/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/ubuntu/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/ubuntu/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/ubuntu/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/ubuntu/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/axolotl/layer.py", line 136, in receive
    self.onMessage(protocolTreeNode)
  File "/home/ubuntu/yowsup/yowsup/layers/axolotl/layer.py", line 160, in onMessage
    self.toUpper(protocolTreeNode)
  File "/home/ubuntu/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/__init**.py", line 188, in receive
    s.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/**init**.py", line 124, in receive
    recv(node)
  File "/home/ubuntu/yowsup/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
    self.toUpper(entity) 
  File "/home/ubuntu/yowsup/yowsup/layers/**init**.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/interface/interface.py", line 78, in receive
    self.entity_callbacks[entityType](entity)
  File "/home/ubuntu/yowsup/yowsup/demos/cli/layer.py", line 529, in onMessage
    MESSAGE_ID=message.getId()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 0: ordinal not in range(128)

**Comment by sowerkoku** [comment]
it seems Latin characters or accents. you are passing values in any way? or occupy only the console?

**Comment by sowerkoku** [comment]
@jlguardi 

Spanish characters are received without problem, but the sending fails.

`
[connected]:/message send Carlos "ñ"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/tcontrol2/yowsup/yowsup/demos/cli/cli.py", line 154, in startInputThread
    wait = self.execCmd(cmd)
  File "/home/tcontrol2/yowsup/yowsup/demos/cli/cli.py", line 138, in execCmd
    return self.doExecCmd(lambda :targetFn(*args))
  File "/home/tcontrol2/yowsup/yowsup/demos/cli/cli.py", line 141, in doExecCmd
    return fn()
  File "/home/tcontrol2/yowsup/yowsup/demos/cli/cli.py", line 138, in <lambda>
    return self.doExecCmd(lambda :targetFn(*args))
  File "/home/tcontrol2/yowsup/yowsup/demos/cli/layer.py", line 384, in message_send
    self.toLower(outgoingMessage)
  File "/home/tcontrol2/yowsup/yowsup/layers/__init__.py", line 79, in toLower
    self.__lower.send(data)
  File "/home/tcontrol2/yowsup/yowsup/layers/__init__.py", line 192, in send
    s.send(data)
  File "/home/tcontrol2/yowsup/yowsup/layers/__init__.py", line 130, in send
    send(entity)
  File "/home/tcontrol2/yowsup/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/home/tcontrol2/yowsup/yowsup/layers/__init__.py", line 134, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/home/tcontrol2/yowsup/yowsup/layers/__init__.py", line 79, in toLower
    self.__lower.send(data)
  File "/home/tcontrol2/yowsup/yowsup/layers/axolotl/layer.py", line 126, in send
    self.handlePlaintextNode(node)
  File "/home/tcontrol2/yowsup/yowsup/layers/axolotl/layer.py", line 194, in handlePlaintextNode
    messageData = self.serializeToProtobuf(node) if v2 else node.getChild("body").getData()
  File "/home/tcontrol2/yowsup/yowsup/layers/axolotl/layer.py", line 528, in serializeToProtobuf
    return self.serializeTextToProtobuf(node)
  File "/home/tcontrol2/yowsup/yowsup/layers/axolotl/layer.py", line 536, in serializeTextToProtobuf
    m.conversation = node.getChild("body").getData()
  File "/usr/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 471, in field_setter
    self._fields[field] = type_checker.CheckValue(new_value)
  File "/usr/lib/python2.7/dist-packages/google/protobuf/internal/type_checkers.py", line 166, in CheckValue
    (proposed_value))
ValueError: '\xc3\xb1' has type bytes, but isn't in 7-bit ASCII encoding. Non-ASCII strings must be converted to unicode objects before being added.
`

**Comment by sowerkoku** [comment]
@ganesansays

in the file: "`yowsup/demos/cli/layer.py`"

find the line: "`def message_send(self, number, content):"`

and says this: "`#outgoingMessage = TextMessageProtocolEntity(content.encode("utf-8") if sys.version_info >= (3,0) else content, to = self.aliasToJid(number))`"

then add this line: "`outgoingMessage = TextMessageProtocolEntity(content.encode("utf-8").decode() if sys.version_info >= (3,0) else content, to = self.aliasToJid(number))`"

or try to upgrade or reinstall axolotl and / or parcel of yowsup:
pip install axolotl
pip install yowsup2

**Comment by ganesansays** [comment]
@jlguardi, I tried both wa16 branch and yowsup2 parcel. I get the following issue.

connected]:Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/usr/local/bin/yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/**init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 124, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 146, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 229, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 266, in handlePreKeyWhisperMessage
    plaintext = sessionCipher.decryptPkmsg(preKeyWhisperMessage)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessioncipher.py", line 96, in decryptPkmsg
    unsignedPreKeyId = self.sessionBuilder.process(sessionRecord, ciphertext)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 50, in process
    unsignedPreKeyId = self.processV3(sessionRecord, message)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 121, in processV3
    parameters.setOurOneTimePreKey(self.preKeyStore.loadPreKey(message.getPreKeyId()).getKeyPair())
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 32, in loadPreKey
    return self.preKeyStore.loadPreKey(preKeyId)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/store/sqlite/liteprekeystore.py", line 20, in loadPreKey
    raise Exception("No such prekeyRecord!")
Exception: No such prekeyRecord!

**Comment by sowerkoku** [comment]
@ganesansays

The mistake I have solved this problem using the master jlguardi and modifying a line of your code.
modification explain it here: #81

**Comment by jlguardi** [comment]
@ganesansays Now your issue is related with missing prekeys (have you deleted axolotl.bd?). Send a message to recipient and it will be fixed.

**Comment by sowerkoku** [comment]
@ganesansays 
true. the last thing you report is not really a problem. You should only delete `$HOME/.yowsup/phone/` and download the keys again

**Comment by ganesansays** [comment]
@jlguardi, @sowerkoku, it seems to be working now ...

Thanks much for your support.
