### ISSUE TITLE
Couldn't receive a media, please help

### ISSUE THREAD

**Issue by msadig** [jlguardi/yowsup#88]
Hi there.
I'm trying to modify "echoclient" demo and receive a image/video from user but wasn't able. When i'm sending text it sends me back but when i'm sending the image it falls. 

**layer.py**

`

from yowsup.layers.interface import YowInterfaceLayer, ProtocolEntityCallback

class EchoLayer(YowInterfaceLayer):

```
@ProtocolEntityCallback("message")
def onMessage(self, messageProtocolEntity):

    print(messageProtocolEntity.getType())

    if messageProtocolEntity.getType() == 'text':
        self.onTextMessage(messageProtocolEntity)
    elif messageProtocolEntity.getType() == 'media':
        self.onMediaMessage(messageProtocolEntity)


    self.toLower(messageProtocolEntity.ack())
    self.toLower(messageProtocolEntity.ack(True))


@ProtocolEntityCallback("receipt")
def onReceipt(self, entity):
    self.toLower(entity.ack())

def onTextMessage(self, messageProtocolEntity):
    self.toLower(messageProtocolEntity.forward(messageProtocolEntity.getFrom()))
    # just print info
    print("Echoing %s to %s" % (messageProtocolEntity.getBody(), messageProtocolEntity.getFrom(False)))

def onMediaMessage(self, messageProtocolEntity):
    # just print info
    if messageProtocolEntity.getMediaType() == "image":
        print("Echoing image %s to %s" % (messageProtocolEntity.url, messageProtocolEntity.getFrom(False)))

    elif messageProtocolEntity.getMediaType() == "location":
        print("Echoing location (%s, %s) to %s" % (
        messageProtocolEntity.getLatitude(), messageProtocolEntity.getLongitude(),
        messageProtocolEntity.getFrom(False)))

    elif messageProtocolEntity.getMediaType() == "vcard":
        print("Echoing vcard (%s, %s) to %s" % (
        messageProtocolEntity.getName(), messageProtocolEntity.getCardData(), messageProtocolEntity.getFrom(False)))
```

`

**run.py**

`

from yowsup.stacks import  YowStackBuilder
from layer import EchoLayer
from yowsup.layers.auth import AuthError
from yowsup.layers import YowLayerEvent
from yowsup.layers.network import YowNetworkLayer

credentials = ("phone", "password") # replace with your phone and password

class YowsupEchoStack(object):
    def **init**(self, credentials, encryptionEnabled = True):
        stackBuilder = YowStackBuilder()

```
    self.stack = stackBuilder\
        .pushDefaultLayers(encryptionEnabled)\
        .push(EchoLayer)\
        .build()

    self.stack.setCredentials(credentials)

def start(self):
    self.stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))
    try:
        self.stack.loop()
    except AuthError as e:
        print("Authentication Error: %s" % e.message)
```

if **name**==  "**main**":
    stackBuilder = YowsupEchoStack(credentials)
    stackBuilder.start()

`

`File "/webapps/whatsapp/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/axolotl/layer.py", line 315, in handleWhisperMessage
TypeError: ord() expected string of length 1, but int found`

Could you point the direction or any demo app to learn from.

**Comment by sowerkoku** [comment]
`self.toLower(messageProtocolEntity.forward(messageProtocolEntity.getFrom()))`
Put that after:
`self.toLower(messageProtocolEntity.ack(True))`

read here #1648

**Comment by msadig** [comment]
@sowerkoku thanks for the feedback, appreciate it.

But that doesn't solve my problem. I'm still not able to receive photo or video. My current code here after the changes you pointed out:

https://github.com/msadig/yowsup-demo/blob/5d78d7d1427f47e6559c7a5570eae2ac13fd1f34/layer.py

this's what terminal shows:

`'utf-8' codec can't decode byte 0xe3 in position 1: invalid continuation byte
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    stackBuilder.start()
  File "run.py", line 25, in start
    self.stack.loop()
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/stacks/yowstack.py", line 195, in loop
  File "/usr/lib/python3.4/asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.4/asyncore.py", line 153, in poll
    read(obj)
  File "/usr/lib/python3.4/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.4/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.4/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/network/layer.py", line 102, in handle_read
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/network/layer.py", line 110, in receive
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/**init**.py", line 75, in toUpper
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    # just print info
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/**init**.py", line 75, in toUpper
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/**init**.py", line 75, in toUpper
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/coder/layer.py", line 35, in receive
    messageProtocolEntity.getLatitude(), messageProtocolEntity.getLongitude(),
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/**init**.py", line 75, in toUpper
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/logger/layer.py", line 14, in receive

  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/**init**.py", line 75, in toUpper
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/axolotl/layer.py", line 136, in receive
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/axolotl/layer.py", line 158, in onMessage
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/axolotl/layer.py", line 232, in handleEncMessage
  File "/webapps/yowsup.demo/lib/python3.4/site-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/axolotl/layer.py", line 315, in handleWhisperMessage
TypeError: ord() expected string of length 1, but int found`

**Comment by sowerkoku** [comment]
unfortunately not currently use the branch of @jlguardi.

It is failing "location"

tried first:
./yowsup-cli demos -c config.config -e

or if it works in cli:
./yowsup-cli demos -c config.config -y

**Comment by msadig** [comment]
@sowerkoku unfortunately I wasn't able to achieve my goal. What I'm trying to achieve is that to be able receive images and videos from people and then concat them together. 

With the @tgalal's version I'm able to receive the image but image encrypted and I couldn't decrypt to see what is image looks like. With the @jlguardi fork, couldn't able even to receive the image and still getting this **TypeError ord()**.

I'm using python 3.4, do you thing it's related with python version? I can't understand what I'm doing wrong. According to this https://github.com/tgalal/yowsup/issues/1400#issuecomment-203482277, people are able to receive the images

**Comment by msadig** [comment]
As I suspected Python version had something to do with my problem. Finally, with python 2.7 I was able to receive image using @jlguardi's branch.

**Comment by jlguardi** [comment]
I've developed and tested just with python 2.7

**Comment by msadig** [comment]
@jlguardi thanks a lot.
