### ISSUE TITLE
Error when receiving a large txt message

### ISSUE THREAD

**Issue by pcortizona** [jlguardi/yowsup#89]
Auth: Logged in!
[connected]:ERROR:yowsup.layers.axolotl.layer:Received message with old counter: 7, 6
WARNING:yowsup.layers.axolotl.layer:Going to send the delivery receipt myself !
Traceback (most recent call last):
  File "yowsup-cli", line 324, in <module>
    if not parser.process():
  File "yowsup-cli", line 228, in process
    self.startCmdline()
  File "yowsup-cli", line 256, in startCmdline
    stack.start()
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/demos/cli/stack.py", line 27, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(_args, *_kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/**init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/axolotl/layer.py", line 136, in receive
    self.onMessage(protocolTreeNode)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/axolotl/layer.py", line 158, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/axolotl/layer.py", line 232, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/axolotl/layer.py", line 316, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/axolotl/layer.py", line 356, in parseAndHandleMessageProto
    self.handleConversationMessage(node, m.conversation)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/axolotl/layer.py", line 386, in handleConversationMessage
    self.toUpper(messageNode)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/__init**.py", line 188, in receive
    s.receive(data)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/**init**.py", line 124, in receive
    recv(node)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
    self.toUpper(entity) 
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/**init**.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/layers/interface/interface.py", line 78, in receive
    self.entity_callbacks[entityType](entity)
  File "/Users/vic/PYTHON/Yowsup/other/jlguardi/yowsup/demos/cli/layer.py", line 529, in onMessage
    MESSAGE_ID=message.getId()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)

**Comment by sowerkoku** [comment]
@pcortizona 
tgalal branch: [see here](https://github.com/tgalal/yowsup/issues/1646#issuecomment-229545988)
jlguardi branch: [see here](https://github.com/jlguardi/yowsup/issues/81#issuecomment-215622554)
