### ISSUE TITLE
common/tools.py: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by phiresky** [jlguardi/yowsup#94]
```
Traceback (most recent call last):                                        
  File "/usr/bin/yowsup-cli", line 324, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 230, in process
    self.startEcho()
  File "/usr/bin/yowsup-cli", line 259, in startEcho
    from yowsup.demos import echoclient
  File "/usr/lib/python3.5/site-packages/yowsup/demos/echoclient/__init__.py", line 1, in <module>
    from .stack import YowsupEchoStack
  File "/usr/lib/python3.5/site-packages/yowsup/demos/echoclient/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/usr/lib/python3.5/site-packages/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/usr/lib/python3.5/site-packages/yowsup/stacks/yowstack.py", line 4, in <module>
    from yowsup.layers.auth                        import YowCryptLayer, YowAuthenticationProtocolLayer
  File "/usr/lib/python3.5/site-packages/yowsup/layers/auth/__init__.py", line 2, in <module>
    from .layer_authentication import YowAuthenticationProtocolLayer
  File "/usr/lib/python3.5/site-packages/yowsup/layers/auth/layer_authentication.py", line 4, in <module>
    from yowsup.common.tools import TimeTools
  File "/usr/lib/python3.5/site-packages/yowsup/common/tools.py", line 222
    elif ModuleTools.INSTALLED_EXIFTOOL():
                                         ^
TabError: inconsistent use of tabs and spaces in indentation
```

Looks like this should already be fixed in 
https://github.com/jlguardi/yowsup/pull/84

**Comment by bmsleight** [comment]
Please pull #84 as python3 fails otherwise.
